package com.github.tier940.legacycraft.core.logisticspipes;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;

import net.minecraft.launchwrapper.IClassTransformer;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.FieldVisitor;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * ASM transformer that restores three connectivity checks removed from LP 0.10.4.28+.
 *
 * <p>
 * LP 0.10.4.27 had three checks in {@code canPipeConnect_internal} that later versions dropped:
 * <ol>
 * <li>EnderIO conduit ({@code enderIOProxy.isItemConduit}) — emitted only when
 * {@code SimpleServiceLocator} still declares the {@code enderIOProxy} field (removed in LP
 * 0.10.4.49+), so the generated bytecode matches whichever LP version is present.</li>
 * <li>RF Power Supplier ({@code hasRFPowerSupplierUpgrade} + Forge Energy capability check).</li>
 * <li>IC2 EU Power Supplier ({@code getIC2PowerLevel > 0} + {@code IC2Proxy.isEnergySink}).</li>
 * </ol>
 * Without them LP pipes refuse to connect to BC Lasers, IC2 machines, and EnderIO conduits.
 * MJ (BuildCraft Joules) was never checked here in any LP version — no regression.
 *
 * <p>
 * {@code EnumFacing.getOpposite()} has SRG name {@code func_176734_d} in obfuscated jars and
 * MCP name {@code getOpposite} in dev ({@code rfg.deobf}) environments. The name is detected at
 * transform time by scanning existing LP bytecode so injected calls match the runtime environment.
 */
public class PipeTransportTransformer implements IClassTransformer {

    private static final Logger LOGGER = LogManager.getLogger("LCCore/PipeTransportTransformer");

    private static final String TARGET_CLASS = "logisticspipes.transport.PipeTransportLogistics";
    private static final String TARGET_METHOD = "canPipeConnect_internal";
    private static final String TARGET_DESC = "(Lnet/minecraft/tileentity/TileEntity;Lnet/minecraft/util/EnumFacing;)Z";

    private static final String SERVICE_LOCATOR = "logisticspipes/proxy/SimpleServiceLocator";
    private static final String SERVICE_LOCATOR_CLASS_RESOURCE = "logisticspipes/proxy/SimpleServiceLocator.class";
    private static final String INV_UTIL_FIELD = "inventoryUtilFactory";
    private static final String INV_UTIL_FIELD_DESC = "Llogisticspipes/utils/InventoryUtilFactory;";

    private static final String PIPE_TRANSPORT = "logisticspipes/transport/PipeTransportLogistics";
    private static final String CORE_PIPE = "logisticspipes/pipes/basic/CoreUnroutedPipe";
    private static final String UPGRADE_MGR = "logisticspipes/interfaces/IPipeUpgradeManager";
    private static final String ENUM_FACING = "net/minecraft/util/EnumFacing";
    private static final String TILE_ENTITY = "net/minecraft/tileentity/TileEntity";

    // SRG name used in obfuscated (production) jars; dev jars use "getOpposite"
    private static final String ENUM_FACING_OPPOSITE_SRG = "func_176734_d";
    private static final String ENUM_FACING_OPPOSITE_DESC = "()L" + ENUM_FACING + ";";

    private static final String ENDER_IO_PROXY_FIELD = "enderIOProxy";
    private static final String ENDER_IO_PROXY_IFACE = "logisticspipes/proxy/interfaces/IEnderIOProxy";
    private static final String ENDER_IO_PROXY_FIELD_DESC = "Llogisticspipes/proxy/interfaces/IEnderIOProxy;";

    // Used for RF capability check — bypasses canReceive() so the pipe stub is always visible
    // to any Forge Energy receiver; actual power delivery in requestRFPower() still gates on
    // isEnergyReceiver (which checks canReceive()), so no power is wasted to full batteries.
    private static final String CAPABILITY_ENERGY_CLASS = "net/minecraftforge/energy/CapabilityEnergy";
    private static final String CAPABILITY_ENERGY_FIELD = "ENERGY";
    private static final String CAPABILITY_ENERGY_FIELD_DESC = "Lnet/minecraftforge/common/capabilities/Capability;";
    private static final String HAS_CAPABILITY_DESC = "(Lnet/minecraftforge/common/capabilities/Capability;Lnet/minecraft/util/EnumFacing;)Z";

    private static final String IC2_PROXY_IFACE = "logisticspipes/proxy/interfaces/IIC2Proxy";
    private static final String IC2_PROXY_FIELD = "IC2Proxy";
    private static final String IC2_PROXY_FIELD_DESC = "Llogisticspipes/proxy/interfaces/IIC2Proxy;";

    // Null until first probe; true/false thereafter. Boolean (boxed) so null encodes 'not yet probed'.
    private Boolean cachedEnderIOProxyPresent = null;

    /**
     * Probes the LP {@code SimpleServiceLocator.class} resource directly rather than via
     * {@code Class.forName} to avoid triggering LP class initialization during transform time.
     * Returns {@code true} only when the field still exists in the installed LP jar.
     */
    private boolean detectEnderIOProxy() {
        if (cachedEnderIOProxyPresent != null) return cachedEnderIOProxyPresent;
        try (InputStream is = Thread.currentThread().getContextClassLoader()
                .getResourceAsStream(SERVICE_LOCATOR_CLASS_RESOURCE)) {
            // is == null means SimpleServiceLocator.class is not on the classpath at all (LP absent).
            if (is == null) {
                cachedEnderIOProxyPresent = false;
                return false;
            }
            ClassReader cr = new ClassReader(readFully(is));
            final boolean[] found = { false };
            cr.accept(
                    new ClassVisitor(Opcodes.ASM5) {

                        @Override
                        public FieldVisitor visitField(
                                                       int access,
                                                       String name,
                                                       String desc,
                                                       String sig,
                                                       Object value) {
                            if (ENDER_IO_PROXY_FIELD.equals(name)) found[0] = true;
                            return null;
                        }
                    },
                    // SKIP_CODE: we only need field declarations, not method bodies — safe and faster.
                    ClassReader.SKIP_CODE | ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
            cachedEnderIOProxyPresent = found[0];
        } catch (Exception e) {
            LOGGER.debug("Could not probe SimpleServiceLocator for enderIOProxy field; assuming absent", e);
            cachedEnderIOProxyPresent = false;
        }
        return cachedEnderIOProxyPresent;
    }

    /**
     * Scans canPipeConnect_internal for an INVOKEVIRTUAL on EnumFacing that returns EnumFacing
     * with no parameters — that is getOpposite(). LP uses the SRG name in obfuscated jars and
     * the MCP name after rfg.deobf(). Using whatever name LP itself uses avoids NoSuchMethodError
     * in both environments.
     */
    private String detectEnumFacingOppositeMethod(byte[] classBytes) {
        // Single-element array: the standard Java 8 pattern for mutating a variable inside an anonymous inner class.
        final String[] result = { ENUM_FACING_OPPOSITE_SRG };
        new ClassReader(classBytes).accept(
                new ClassVisitor(Opcodes.ASM5) {

                    @Override
                    public MethodVisitor visitMethod(
                                                     int access,
                                                     String name,
                                                     String desc,
                                                     String sig,
                                                     String[] exceptions) {
                        if (!TARGET_METHOD.equals(name) || !TARGET_DESC.equals(desc)) return null;
                        return new MethodVisitor(Opcodes.ASM5) {

                            @Override
                            public void visitMethodInsn(
                                                        int opcode,
                                                        String owner,
                                                        String mName,
                                                        String mDesc,
                                                        boolean itf) {
                                if (opcode == Opcodes.INVOKEVIRTUAL && ENUM_FACING.equals(owner) &&
                                        ENUM_FACING_OPPOSITE_DESC.equals(mDesc)) {
                                    result[0] = mName;
                                }
                            }
                        };
                    }
                },
                ClassReader.SKIP_FRAMES | ClassReader.SKIP_DEBUG);
        return result[0];
    }

    // 4096-byte read buffer — a standard I/O chunk size; the returned array is fully owned
    // by the caller (ByteArrayOutputStream.toByteArray() always allocates a fresh copy).
    private static byte[] readFully(InputStream is) throws Exception {
        ByteArrayOutputStream buf = new ByteArrayOutputStream();
        byte[] tmp = new byte[4096];
        int n;
        while ((n = is.read(tmp)) != -1) buf.write(tmp, 0, n);
        return buf.toByteArray();
    }

    @Override
    public byte[] transform(String name, String transformedName, byte[] bytes) {
        if (!TARGET_CLASS.equals(transformedName) || bytes == null) return bytes;

        // emitEnderIO and enumFacingOpposite are effectively-final locals captured by the
        // anonymous ClassVisitor / MethodVisitor inner classes below (Java 8 capture rules).
        final boolean emitEnderIO = detectEnderIOProxy();
        final String enumFacingOpposite = detectEnumFacingOppositeMethod(bytes);

        ClassReader reader = new ClassReader(bytes);
        // COMPUTE_FRAMES recalculates the entire StackMapTable, required when adding new
        // branch targets. COMPUTE_MAXS alone does not update frames and causes VerifyError.
        // getCommonSuperClass falls back gracefully if a type is unresolvable during early
        // LaunchWrapper class transformation.
        ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_FRAMES) {

            @Override
            protected String getCommonSuperClass(String type1, String type2) {
                try {
                    return super.getCommonSuperClass(type1, type2);
                } catch (Exception e) {
                    return "java/lang/Object";
                }
            }
        };
        // Single-element array lets the anonymous ClassVisitor mutate a flag visible in the enclosing transform()
        // scope.
        boolean[] patchApplied = { false };

        ClassVisitor cv = new ClassVisitor(Opcodes.ASM5, writer) {

            @Override
            public MethodVisitor visitMethod(
                                             int access,
                                             String mName,
                                             String desc,
                                             String signature,
                                             String[] exceptions) {
                MethodVisitor mv = super.visitMethod(access, mName, desc, signature, exceptions);
                if (!TARGET_METHOD.equals(mName) || !TARGET_DESC.equals(desc)) return mv;

                return new MethodVisitor(Opcodes.ASM5, mv) {

                    private boolean patched = false;

                    @Override
                    public void visitFieldInsn(
                                               int opcode, String owner, String fName, String fDesc) {
                        // Inject before the first SimpleServiceLocator.inventoryUtilFactory access,
                        // which is the earliest stable landmark present in all target LP versions.
                        // It appears before every existing early-return guard in the original method,
                        // so our injected block executes before any of them can short-circuit.
                        if (!patched && opcode == Opcodes.GETSTATIC && SERVICE_LOCATOR.equals(owner) &&
                                INV_UTIL_FIELD.equals(fName) && INV_UTIL_FIELD_DESC.equals(fDesc)) {
                            patched = true;
                            patchApplied[0] = true;
                            emitRestoredChecks();
                        }
                        super.visitFieldInsn(opcode, owner, fName, fDesc);
                    }

                    // Emits bytecode equivalent to the three connectivity checks removed in LP 0.10.4.28+.
                    // ALOAD_0 = this (PipeTransportLogistics), ALOAD_1 = tile (TileEntity param),
                    // ALOAD_2 = facing (EnumFacing param) — derived from TARGET_DESC.
                    private void emitRestoredChecks() {
                        // skipRF: fallthrough when RF upgrade is absent; also the entry point for the IC2 block.
                        // returnTrue: shared true-return target reached by any passing check.
                        // skipAll: exit point when all three checks fail; execution continues into original body.
                        Label skipRF = new Label();
                        Label returnTrue = new Label();
                        Label skipAll = new Label();

                        if (emitEnderIO) {
                            // 1. EnderIO: if (enderIOProxy.isItemConduit(tile, facing.opp())) return true
                            super.visitFieldInsn(
                                    Opcodes.GETSTATIC,
                                    SERVICE_LOCATOR,
                                    ENDER_IO_PROXY_FIELD,
                                    ENDER_IO_PROXY_FIELD_DESC);
                            super.visitVarInsn(Opcodes.ALOAD, 1);
                            super.visitVarInsn(Opcodes.ALOAD, 2);
                            super.visitMethodInsn(
                                    Opcodes.INVOKEVIRTUAL,
                                    ENUM_FACING,
                                    enumFacingOpposite,
                                    ENUM_FACING_OPPOSITE_DESC,
                                    false);
                            super.visitMethodInsn(
                                    Opcodes.INVOKEINTERFACE,
                                    ENDER_IO_PROXY_IFACE,
                                    "isItemConduit",
                                    "(L" + TILE_ENTITY + ";L" + ENUM_FACING + ";)Z",
                                    true);
                            super.visitJumpInsn(Opcodes.IFNE, returnTrue);
                        }

                        // 2. RF: if (!hasRFPowerSupplierUpgrade()) goto ic2
                        super.visitVarInsn(Opcodes.ALOAD, 0);
                        super.visitMethodInsn(
                                Opcodes.INVOKEVIRTUAL,
                                PIPE_TRANSPORT,
                                "getPipe",
                                "()L" + CORE_PIPE + ";",
                                false);
                        super.visitMethodInsn(
                                Opcodes.INVOKEVIRTUAL,
                                CORE_PIPE,
                                "getUpgradeManager",
                                "()L" + UPGRADE_MGR + ";",
                                false);
                        super.visitMethodInsn(
                                Opcodes.INVOKEINTERFACE,
                                UPGRADE_MGR,
                                "hasRFPowerSupplierUpgrade",
                                "()Z",
                                true);
                        // IFEQ: jump to skipRF (IC2 block) when hasRFPowerSupplierUpgrade() == false.
                        super.visitJumpInsn(Opcodes.IFEQ, skipRF);
                        // if (tile.hasCapability(CapabilityEnergy.ENERGY, facing.opp())) return true
                        super.visitVarInsn(Opcodes.ALOAD, 1);
                        super.visitFieldInsn(
                                Opcodes.GETSTATIC,
                                CAPABILITY_ENERGY_CLASS,
                                CAPABILITY_ENERGY_FIELD,
                                CAPABILITY_ENERGY_FIELD_DESC);
                        super.visitVarInsn(Opcodes.ALOAD, 2);
                        super.visitMethodInsn(
                                Opcodes.INVOKEVIRTUAL,
                                ENUM_FACING,
                                enumFacingOpposite,
                                ENUM_FACING_OPPOSITE_DESC,
                                false);
                        super.visitMethodInsn(
                                Opcodes.INVOKEVIRTUAL,
                                TILE_ENTITY,
                                "hasCapability",
                                HAS_CAPABILITY_DESC,
                                false);
                        // IFNE: jump to returnTrue if hasCapability() returned true (!= 0).
                        super.visitJumpInsn(Opcodes.IFNE, returnTrue);

                        // 3. IC2 EU: if (getIC2PowerLevel() <= 0) goto skip
                        super.visitLabel(skipRF);
                        super.visitVarInsn(Opcodes.ALOAD, 0);
                        super.visitMethodInsn(
                                Opcodes.INVOKEVIRTUAL,
                                PIPE_TRANSPORT,
                                "getPipe",
                                "()L" + CORE_PIPE + ";",
                                false);
                        super.visitMethodInsn(
                                Opcodes.INVOKEVIRTUAL,
                                CORE_PIPE,
                                "getUpgradeManager",
                                "()L" + UPGRADE_MGR + ";",
                                false);
                        super.visitMethodInsn(
                                Opcodes.INVOKEINTERFACE,
                                UPGRADE_MGR,
                                "getIC2PowerLevel",
                                "()I",
                                true);
                        // IFLE: jump to skipAll when getIC2PowerLevel() <= 0 (no IC2 upgrade configured).
                        super.visitJumpInsn(Opcodes.IFLE, skipAll);
                        // if (IC2Proxy.isEnergySink(tile)) return true
                        super.visitFieldInsn(
                                Opcodes.GETSTATIC,
                                SERVICE_LOCATOR,
                                // SimpleServiceLocator.IC2Proxy — the static field holding the IC2 proxy instance.
                                IC2_PROXY_FIELD,
                                IC2_PROXY_FIELD_DESC);
                        super.visitVarInsn(Opcodes.ALOAD, 1);
                        super.visitMethodInsn(
                                Opcodes.INVOKEINTERFACE,
                                IC2_PROXY_IFACE,
                                "isEnergySink",
                                "(L" + TILE_ENTITY + ";)Z",
                                true);
                        // IFEQ: jump to skipAll when isEnergySink() returned false (== 0).
                        super.visitJumpInsn(Opcodes.IFEQ, skipAll);

                        super.visitLabel(returnTrue);
                        super.visitInsn(Opcodes.ICONST_1);
                        super.visitInsn(Opcodes.IRETURN);

                        super.visitLabel(skipAll);
                    }
                };
            }
        };

        // Flag 0: no skipping — we need to visit and rewrite the full method body including
        // instructions, frames, and debug info (unlike the probe readers above).
        reader.accept(cv, 0);
        if (patchApplied[0]) {
            LOGGER.info(
                    "Patched LP canPipeConnect_internal: restored RF/IC2{} energy checks (EnumFacing.{})",
                    emitEnderIO ? "/EnderIO" : "",
                    enumFacingOpposite);
        } else {
            // Landmark not found — LP changed its internal structure; patch silently did nothing.
            LOGGER.warn(
                    "PipeTransportTransformer: injection landmark ({}.{}) not found in {}; patch NOT applied",
                    SERVICE_LOCATOR, INV_UTIL_FIELD, TARGET_CLASS);
        }
        return writer.toByteArray();
    }
}
